format_version: 3
pipelines:
  Akka-http-docker-publish-yaml:
    group: Bootcamp-yaml
    label_template: ${GO_DEPENDENCY_LABEL_AKKA_HTTP_BUILD_YAML}
    lock_behavior: none
    display_order: -1
    materials:
      Akka-http-build-yaml:
        ignore_for_scheduling: false
        pipeline: Akka-http-build-yaml
        stage: building-jar
      git:
        git: https://github.com/dhawalshah48/CI-CD
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
      - fetching-jar-making-docker-image:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            fetching-making:
              timeout: 0
              tasks:
                - fetch:
                    is_file: true
                    source: target/scala-2.12/CI-CD-assembly-0.1.jar
                    destination: ''
                    pipeline: Akka-http-build-yaml
                    stage: building-jar
                    job: build-jar
                    artifact_origin: gocd
                    run_if: passed
                - exec:
                    command: sh
                    arguments:
                      - -c
                      - docker build . -t dhawalshah48/go-pipeline:$GO_DEPENDENCY_LABEL_AKKA_HTTP_BUILD_YAML
                    run_if: passed
      - publishing-docker-image:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            publish:
              timeout: 0
              tasks:
                - exec:
                    command: sh
                    arguments:
                      - -c
                      - docker push dhawalshah48/go-pipeline:$GO_DEPENDENCY_LABEL_AKKA_HTTP_BUILD_YAML
                    run_if: passed
